version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: taskboard-postgres
    environment:
      POSTGRES_DB: taskboarddb
      POSTGRES_USER: taskboarduser
      POSTGRES_PASSWORD: taskboardpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: